apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    name: backend
spec:
  containers:
  - name: backend
    image: oktadr/backend:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    env:
      - name:  DefaultConnection
        value: Host=10.98.205.160;Username=okta;Password=okta;Database=postgres
      - name:  URL_FRONTEND
        value: http://localhost:5173

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    name: backend
  ports:
  - port: 8080
    targetPort: 8080
 

