apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  containers:
  - name: frontend
    image: oktadr/frontend:latest
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits: 
        cpu : "1"
        memory: "2Gi"
    ports:
      - containerPort: 5173
    env:
      - name:  VITE_API_URL
        value: http://localhost:8080/api/
      - name:  VITE_CHAT_URL
        value: http://localhost:8080/conversation/
      - name:  VITE_COMMENT_URL
        value: http://localhost:8080/chat/
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    name: frontend
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 31173
