apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  containers:
  - name: postgres
    image: postgres
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: "okta"
      - name: POSTGRES_DB
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "okta"
---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    name: postgres
  ports:
  - port: 5432
    targetPort: 5432
    
